#!/usr/bin/env python3
"""One-off data-hygiene migration (2026-07-06).

Three operations, all inside one transaction on the DB passed as argv[1]:

  A. Cambridge Option B — remap stages 1–6 to US grade = stage−1 (1→K … 6→5),
     removing the 6/7 grade discontinuity. Stages 7–9 already correct; C*/E* → HS.
  B. FK-safe de-duplication — collapse rows that are identical on
     (system, grade, case-insensitive domain, standard_text). The survivor is the
     most crosswalk-connected id; every loser's FK references (keywords,
     crosswalk_mappings, standard_relationships, sub_standards) are REMAPPED onto
     the survivor before the loser is deleted, so nothing cascades away. Duplicate
     refs that would violate a UNIQUE constraint are dropped (they duplicate the
     survivor's). Self-references created by remap are removed.
  C. Singapore domain-casing normalisation — UPPERCASE domains → canonical title case.

  Also opportunistically clears PRE-EXISTING orphaned crosswalk/embedding/keyword
  rows (FK debt from earlier deletions) so PRAGMA foreign_key_check ends clean.

Usage:  uv run python scripts/dedup_pass.py /path/to/copy.db
Read-only on the original — always run against a COPY, verify, then promote.
"""
import re
import sqlite3
import sys

CAMBRIDGE_STAGE_GRADE = {1: "K", 2: "1", 3: "2", 4: "3", 5: "4", 6: "5"}
SG_DOMAIN_CANON = {
    "NUMBER AND ALGEBRA":        "Number and Algebra",
    "GEOMETRY AND MEASUREMENT":  "Geometry and Measurement",
    "MEASUREMENT AND GEOMETRY":  "Measurement and Geometry",
    "STATISTICS AND PROBABILITY": "Statistics and Probability",
}
_CAMB_STAGE = re.compile(r"^CAMBRIDGE\.MATH\.(\d+)")
# A trailing autogenerated numeric id segment ('.614045'). Two identical-text rows
# whose ids differ ONLY here are a genuine double-ingest; ids differing in a
# structured sub-code ('.PS4-1' vs '.PS4-4', '.4.a' vs '.4.c', '.P.A' vs '.A') may
# be distinct standards that merely share text, so those groups are NOT collapsed.
# Require 4+ digits so a small MEANINGFUL standard number ('W.1.4' vs 'W.1.10',
# both placeholder stubs) is never mistaken for an opaque ingest id.
_TRAIL_NUM = re.compile(r"\.\d{4,}$")


def _stem(i: str) -> str:
    return _TRAIL_NUM.sub("", i)


def counts(c):
    q = lambda s: c.execute(s).fetchone()[0]
    return {
        "standards":     q("SELECT COUNT(*) FROM standards"),
        "embeddings":    q("SELECT COUNT(*) FROM embeddings"),
        "crosswalks":    q("SELECT COUNT(*) FROM crosswalk_mappings"),
        "relationships": q("SELECT COUNT(*) FROM standard_relationships"),
        "keywords":      q("SELECT COUNT(*) FROM keywords"),
        "fk_violations": len(c.execute("PRAGMA foreign_key_check").fetchall()),
    }


def main(db_path):
    c = sqlite3.connect(db_path)
    c.execute("PRAGMA foreign_keys = ON")
    before = counts(c)
    print(f"BEFORE: {before}")

    c.execute("BEGIN")

    # ── A. Cambridge Option B ────────────────────────────────────────────────
    camb = c.execute(
        "SELECT id, grade FROM standards WHERE system='cambridge'"
    ).fetchall()
    camb_updates = 0
    for sid, grade in camb:
        m = _CAMB_STAGE.match(sid)
        if not m:
            continue
        stage = int(m.group(1))
        target = CAMBRIDGE_STAGE_GRADE.get(stage)
        if target is not None and target != grade:
            c.execute("UPDATE standards SET grade=? WHERE id=?", (target, sid))
            camb_updates += 1
    print(f"A. Cambridge stage 1–6 regraded: {camb_updates} rows")

    # ── B. FK-safe de-duplication ────────────────────────────────────────────
    # Group rows identical on (system, grade, UPPER(domain), text); n>1.
    groups: dict[tuple, list[str]] = {}
    for sid, key in c.execute(
        "SELECT id, system||'\x1f'||grade||'\x1f'||upper(coalesce(domain,''))"
        "||'\x1f'||standard_text AS k "
        "FROM standards WHERE length(trim(standard_text))>0"
    ):
        groups.setdefault(key, []).append(sid)
    # Only collapse groups whose ids differ solely in a trailing numeric segment
    # (opaque double-ingest); exclude structured-sub-code look-alikes.
    dup_groups = {
        k: v for k, v in groups.items()
        if len(v) > 1
        and len({_stem(i) for i in v}) == 1
        and all(_stem(i) != i for i in v)
    }

    # Crosswalk connectivity per candidate id (source + target refs).
    conn_score: dict[str, int] = {}
    for tbl_col in ("source_id", "target_id"):
        for cid, n in c.execute(
            f"SELECT {tbl_col}, COUNT(*) FROM crosswalk_mappings GROUP BY {tbl_col}"
        ):
            conn_score[cid] = conn_score.get(cid, 0) + n

    # Survivor = most crosswalk-connected, tie-break shortest then smallest id.
    dup_map: list[tuple[str, str]] = []  # (loser, survivor)
    for ids in dup_groups.values():
        survivor = min(ids, key=lambda i: (-conn_score.get(i, 0), len(i), i))
        for i in ids:
            if i != survivor:
                dup_map.append((i, survivor))

    c.execute("CREATE TEMP TABLE dup_map(loser TEXT PRIMARY KEY, survivor TEXT)")
    c.executemany("INSERT INTO dup_map VALUES (?,?)", dup_map)
    n_losers = len(dup_map)
    print(f"B. Duplicate groups: {len(dup_groups)}  losers to collapse: {n_losers}")

    # Remap FK references loser→survivor (OR IGNORE drops UNIQUE-conflicting dups).
    remap_sql = [
        "UPDATE OR IGNORE keywords SET standard_id=(SELECT survivor FROM dup_map WHERE loser=keywords.standard_id) WHERE standard_id IN (SELECT loser FROM dup_map)",
        "UPDATE OR IGNORE sub_standards SET parent_id=(SELECT survivor FROM dup_map WHERE loser=sub_standards.parent_id) WHERE parent_id IN (SELECT loser FROM dup_map)",
        "UPDATE OR IGNORE crosswalk_mappings SET source_id=(SELECT survivor FROM dup_map WHERE loser=crosswalk_mappings.source_id) WHERE source_id IN (SELECT loser FROM dup_map)",
        "UPDATE OR IGNORE crosswalk_mappings SET target_id=(SELECT survivor FROM dup_map WHERE loser=crosswalk_mappings.target_id) WHERE target_id IN (SELECT loser FROM dup_map)",
        "UPDATE OR IGNORE standard_relationships SET source_id=(SELECT survivor FROM dup_map WHERE loser=standard_relationships.source_id) WHERE source_id IN (SELECT loser FROM dup_map)",
        "UPDATE OR IGNORE standard_relationships SET target_id=(SELECT survivor FROM dup_map WHERE loser=standard_relationships.target_id) WHERE target_id IN (SELECT loser FROM dup_map)",
    ]
    for s in remap_sql:
        c.execute(s)

    # Drop self-references produced by remap (loser was linked to its survivor).
    c.execute("DELETE FROM crosswalk_mappings WHERE source_id=target_id")
    c.execute("DELETE FROM standard_relationships WHERE source_id=target_id")

    # Losers' own embeddings are redundant (survivor keeps its own); drop them,
    # then delete the loser standards (remaining skipped-dup refs cascade away).
    c.execute("DELETE FROM embeddings WHERE standard_id IN (SELECT loser FROM dup_map)")
    c.execute("DELETE FROM standards WHERE id IN (SELECT loser FROM dup_map)")

    # ── C. Singapore domain casing ───────────────────────────────────────────
    sg_fixed = 0
    for up, canon in SG_DOMAIN_CANON.items():
        cur = c.execute(
            "UPDATE standards SET domain=? WHERE system='sg-moe' AND domain=?",
            (canon, up),
        )
        sg_fixed += cur.rowcount
    print(f"C. Singapore domains title-cased: {sg_fixed} rows")

    # ── Opportunistic: clear pre-existing FK orphans ─────────────────────────
    # (baseline orphans live only in crosswalks/embeddings/keywords; the remap +
    # cascade cannot create relationship orphans, so that table is skipped.)
    # NOT EXISTS uses the standards PK index — far cheaper than NOT IN here.
    orphan_sql = [
        "DELETE FROM crosswalk_mappings WHERE NOT EXISTS (SELECT 1 FROM standards s WHERE s.id=source_id) OR NOT EXISTS (SELECT 1 FROM standards s WHERE s.id=target_id)",
        "DELETE FROM embeddings WHERE NOT EXISTS (SELECT 1 FROM standards s WHERE s.id=standard_id)",
        "DELETE FROM keywords WHERE NOT EXISTS (SELECT 1 FROM standards s WHERE s.id=standard_id)",
    ]
    for s in orphan_sql:
        c.execute(s)

    c.execute("COMMIT")

    after = counts(c)
    print(f"AFTER:  {after}")
    print("DELTA:  " + ", ".join(
        f"{k} {after[k]-before[k]:+d}" for k in before))
    ic = c.execute("PRAGMA integrity_check").fetchone()[0]
    print(f"integrity_check: {ic}")
    print(f"fk_violations after: {after['fk_violations']}")
    c.close()
    if after["fk_violations"] != 0 or ic != "ok":
        sys.exit("FAILED: integrity or FK violations remain")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit("usage: dedup_pass.py <db_path>")
    main(sys.argv[1])
